name: ci

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - { toolchain: nightly }
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust.toolchain }}
          default: true

      - name: Install Rust Source
        run: rustup component add rust-src
      
      - name: Install GNU Binutils
        run: sudo apt-get update && sudo apt-get install binutils-arm-none-eabi

      - name: Build The Examples (Link With GNU, weak compiler intrinsics)
        run: cargo build --examples
      
      - name: Delete the .cargo/config.toml
        run: rm -fr .cargo/config.toml

      - name: Build The Examples (Link With LLD, strong compiler intrinsics)
        run: cargo build --examples --target=thumbv4t-none-eabi -Zbuild-std=core -Clink-arg=-Tlinker_scripts/mono_boot.ld

      - name: Build The Crate With No Default Features (build script usage simulation)
        run: cargo build --no-default-features
